### ISSUE TITLE
Does not work with jQuery 1.9 up

### ISSUE THREAD

**Issue by swinggraphics** [drewwilson/TipTip#20]
If I switch back to jQuery 1.8.3, it works. There are no errors in the console. You may message me for link to private dev site with the issue. I'll follow-up if I figure out the specific issue.

**Comment by PandaWood** [comment]
Actually, we're using TipTip with jquery v2.1.4  - and it's working fine. Maybe it's your selector?
I realize it's more than a year since you wrote your issue... just thought I'd put my hand up given the opposite experience.

**Comment by danimesq** [comment]
@swinggraphics
This repo is stopped since 2010 year.
This is my updated fork with pull requests: https://github.com/WS-js/TipTip

**Comment by PandaWood** [comment]
Thanks Daniel,
Yeah, it seems like GitHub would benefit from some way of being able to emphasize one repo over another as being the "main one" that users are hovering to ie in this case, your repo.

**Comment by swinggraphics** [comment]
Maybe the readme could say this repo is abandoned and link to the new one?
